package(default_visibility = ["//visibility:public"])

py_library(
    name = "logging",
    srcs = [
        "__init__.py",
    ],
    deps = [
        "//external:coloredlogs",
    ],
    # srcs_version = "PY3",
)
