py_binary(
    name = "codeforces-tagstat",
    srcs = [
        "tagstat.py",
    ],
    deps = [
        "//libs/logging:logging",
        "//libs/api:api",
        "//libs/ml:ml",
    ],
    main = "tagstat.py",
    # srcs_version = "PY3",
)
